[package]
name = "mymacros"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "*"
serde = "*"
log = "*"

[dev-dependencies]
env_logger = "*"
reqwest = "*"
tokio = { version = "*", features = ["rt", "macros"] }
anyhow = "*"